config/routes.rb
CraigslistJrRails::Application.routes.draw do

  resources :categories, only: [:new, :index, :create, :show] do
    resources :posts, only: [:new, :create, :show]
  end

  root :to => 'categories#index'

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    redirect_to categories_path
  end

  def show
    @category = Category.find(params[:id])
    @posts = Post.where(category_id: params[:id])
  end

  private

  def category_params
    params.require(:category).permit([:name])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @post = @category.posts.build
  end

  def create
    category = Category.find(params[:category_id])
    @post = category.posts.create(posts_params)
    redirect_to category_path(category)
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def posts_params
    params.require(:post).permit([:title, :description, :category_id])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.erb
<h1>Craigslist Jr</h1>
<% @categories.each do |category| %>
  <h4><%= link_to category.name, category_path(category) %></h4>
<% end %>

<%= link_to "Create", new_category_path(@category) %>

app/views/categories/new.erb
<h1>Create a New Category</h1>
<%= form_for @category do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Create" %>
<% end %>

app/views/categories/show.erb
<h2><%= @category.name %></h2>

<% if @posts %>
  <% @posts.each do |p| %>
    <%= link_to p.title, category_post_path(@category.id, p.id) %>
    <br>
  <% end %>
<% end %>
<br>
<%= link_to "Make a new post", new_category_post_path(@category) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CraigslistJrRails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/new.html.erb
<h2><%= 'Create New ' + @category.name + ' Post' %></h2>
<%= form_for @post, { url: category_posts_path(@category) } do |form| %>
<%= label_tag(:title, "Title of Post") %>
<%= form.text_field(:title) %>
<%= label_tag(:description, "Description") %>
<%= form.text_area(:description) %>
<%= form.submit %>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<div>
  <p><%= @post.description %></p>
</div>